### ISSUE TITLE
Split information missing

### ISSUE THREAD

**Issue by pcp16** [srijandas07/LSTM_action_recognition#1]
the LSTM trainer expects text files that define the splits used. These files are not available with the code, nor the Toyota SmartHomes dataset (AFAIK). What is the expected format of these files? Can you make them available here? Thanks!

**Comment by srijandas07** [comment]
The split files are text files with the video names. The split file depends on your dataset ( the splits).
The data for Toyota smarthome is available at https://project.inria.fr/toyotasmarthome/
Let me know if this solves your problem.

**Comment by pcp16** [comment]
Thank toy for your reply! I guess for the cross-subject (CS) training these files contain the training and testing subjects described on the paper. Although "validation" subjects would still be missing.

**Comment by srijandas07** [comment]
Yes true. For validation, I randomly take out 5% of the data from the training file.

**Comment by pcp16** [comment]
Great, that solves the doubt then. Thank you.
